--- #YAML:1.0
name:                Email-Date
version:             1.102
abstract:            Find and Format Date Headers
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Date::Parse:                   2.27
    Email::Abstract:               2.10
    Test::More:                    0.47
    Time::Local:                   1.07
    Time::Piece:                   1.08
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Casey West <casey@geeknest.com>
