# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Email-Date
version:      1.01
version_from: lib/Email/Date.pm
installdirs:  site
requires:
    Email::Abstract:               
    Email::Simple:                 
    Test::More:                    0.47
    Time::Local:                   
    Time::Piece:                   

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
